export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
    theme: {
      extend: {
        "colors": {
                "primary-fixed-dim": "#d3bbff",
                "error-container": "#ffdad6",
                "primary-container": "#5b21b6",
                "on-tertiary-fixed-variant": "#4a4456",
                "inverse-on-surface": "#f0f1f2",
                "surface-container-low": "#f2f3ff",
                "on-primary-fixed-variant": "#581db3",
                "on-error": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "tertiary-fixed": "#e9def5",
                "error": "#ba1a1a",
                "surface-container": "#edeeef",
                "on-primary": "#ffffff",
                "surface-container-high": "#e7e8e9",
                "inverse-primary": "#d3bbff",
                "surface-dim": "#d9dadb",
                "surface-container-highest": "#e1e3e4",
                "on-secondary-fixed": "#3e0022",
                "on-primary-container": "#c7aaff",
                "outline-variant": "#ccc3d6",
                "secondary-container": "#fd56a7",
                "on-tertiary-container": "#beb5ca",
                "on-tertiary": "#ffffff",
                "surface": "#f8f9fa",
                "secondary": "#b4136d",
                "outline": "#7b7485",
                "on-error-container": "#93000a",
                "on-secondary": "#ffffff",
                "tertiary": "#363041",
                "on-primary-fixed": "#250059",
                "on-secondary-container": "#600037",
                "on-surface": "#191c1d",
                "tertiary-container": "#4d4658",
                "secondary-fixed": "#ffd9e4",
                "primary": "#420093",
                "tertiary-fixed-dim": "#cdc2d9",
                "primary-fixed": "#ebddff",
                "background": "#faf8ff",
                "on-secondary-fixed-variant": "#8c0053",
                "on-tertiary-fixed": "#1e1929",
                "surface-tint": "#713dcc",
                "inverse-surface": "#2e3132",
                "secondary-fixed-dim": "#ffb0cd",
                "surface-bright": "#f8f9fa",
                "on-surface-variant": "#4a4453",
                "surface-variant": "#e1e3e4",
                "on-background": "#191c1d"
        },
        "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
        },
        "spacing": {
                "unit": "8px",
                "margin-desktop": "40px",
                "glass-padding": "24px",
                "gutter": "24px",
                "margin-mobile": "16px",
                "container-max": "1280px",
                "bento-gap": "24px"
        },
        "fontFamily": {
                "body-sm": ["Sora"],
                "headline-lg-mobile": ["Sora"],
                "body-md": ["Sora"],
                "body-lg": ["Sora"],
                "display-lg": ["Sora"],
                "display-xl": ["Sora"],
                "headline-lg": ["Sora"],
                "headline-md": ["Sora"],
                "label-md": ["Sora"],
                "label-caps": ["Sora"],
                poppins: ['Poppins', 'sans-serif'],
                Quicksand: ["Quicksand", 'sans-serif'],
               
        },
        "fontSize": {
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "display-xl": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}]
        }
      },
    },
  
  plugins: [],
}
